[tool.poetry]
name = "silver-transform"
version = "0.1.0"
description = ""
authors = ["Egbewatt Nkongho <egbewattnkonghob@gmail.com>"]
readme = "README.md"
packages = [{include = "transform"}]

[tool.poetry.scripts]
serve = "transform.serve:serve"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
