name: CI Tests

on:
    pull_request:
        branches:
            - main
        paths:
            - 'lambdas/**'


jobs:
    test-ingestion-lambda:
        name: Test Ingestion Lambda
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                version: '1.8.0'
                virtualenvs-create: false
                virtualenvs-in-project: true

            - name: Install Dependencies
              run: |
                  chmod +x ./ci/scripts/execute-lambda-command.sh
                  ./ci/scripts/execute-lambda-command.sh ingestion make install

            - name: Run Tests
              run: |
                ./ci/scripts/execute-lambda-command.sh ingestion make test

    test-silver-transform-lambda:
        name: Test Silver Transformation Lambda
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                version: '1.8.0'
                virtualenvs-create: false
                virtualenvs-in-project: true

            - name: Install Dependencies
              run: |
                chmod +x ./ci/scripts/execute-lambda-command.sh
                ./ci/scripts/execute-lambda-command.sh silver-transform make install

            - name: Run Tests
              run: |
                ./ci/scripts/execute-lambda-command.sh silver-transform make test

    test-gold-transform-lambda:
        name: Test Gold Transformation Lambda
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                version: '1.8.0'
                virtualenvs-create: false
                virtualenvs-in-project: true

            - name: Install Dependencies
              run: |
                chmod +x ./ci/scripts/execute-lambda-command.sh
                ./ci/scripts/execute-lambda-command.sh gold-transform make install

            - name: Run Tests
              run: |
                ./ci/scripts/execute-lambda-command.sh gold-transform make test
                